spring:
  profiles:
    active: dev
server:
  port: 9066
  session:
    timeout: 5400
    cookie:
      name: PGYSESSIONID
---
spring:
  profiles: dev
auth:
  accounts:
    -
      username: admin
      password: 21232f297a57a5a743894a0e4a801fc3
      role: ADMIN
  authType: INTERNAL
  loginPageUrl: /pgy/login.html
  loginApi: /api/pgy/v1/auth/login
  loginSuccessUrl: /pgy/#/homepage
  logoutApi: /api/pgy/v1/auth/logout
  logoutSuccessUrl: /pgy/
  authPatterns:
    - /api/pgy/**
    - /api/common/**
    #- /files/**
  ignorePatterns:
    - /pgy/**
    - /assets/**
    - /dep/**
jdbc:
  dbReadBatchSize: 5000
  dbWriteBatchSize: 1000
  dbUrl: jdbc:mysql://localhost/pgy?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
  dbUser: tester
  dbPassword: 123456
upload:
  type: LOCAL
  local:
    dir: ./Downloads/pgy
    prefix: http://localhost:9066/files/
    resPatterns: /files/**
    location: file:./Downloads/pgy/
  bos:
    ak: ak
    sk: sk
    bucket: bucket
    uploadDir:
material:
  coursewareIcon: ./1.png
  classicIcon: ./1.png
  exerciseIcon: ./1.png
schedule:
  userCheckEnable: false
  userCheckCron: "0 0 0 * * *"
